# Making Python More Efficient with Numpy: Array Indexing

**Outline:**

* [Data Types](#Data-Types)
* [Arrays](#Arrays)
* [Array Indexing](#Array-Indexing)

In [1]:
import numpy as np

## Data Types

In [2]:
x = np.array([1, 2])
type(x)

numpy.ndarray

In [3]:
x.dtype

dtype('int64')

In [4]:
x = np.array([1.0, 2.0])
x.dtype

dtype('float64')

## Arrays

In [5]:
a = np.array([1, 2, 3])
print(a.shape)

(3,)


In [6]:
a[1]

2

In [7]:
b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b.shape)

(2, 3)


In [8]:
print(b[0, 0], b[0, 1], b[1, 0])

1 2 4


In [9]:
a = np.zeros((2, 2))
print(a)

[[ 0.  0.]
 [ 0.  0.]]


In [10]:
b = np.ones((1, 2))
print(b)

[[ 1.  1.]]


In [11]:
c = np.full((2, 2), 7, dtype='float')
print(c)

[[ 7.  7.]
 [ 7.  7.]]


In [12]:
d = np.eye(3)
print(d)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [13]:
e = np.random.random((3, 3))
print(e)

[[ 0.34266262  0.88871628  0.89293934]
 [ 0.39853289  0.2779861   0.62419866]
 [ 0.12434072  0.98649679  0.66235017]]


## Array Indexing

In [14]:
a = np.array([[1, 2,  3,  4],
              [5, 6,  7,  8],
              [9, 10, 11, 12]])
print(a[0, 1])

2


In [15]:
print(a[:2, 1:3])

[[2 3]
 [6 7]]


In [16]:
print(a[1, :])

[5 6 7 8]


In [17]:
print(a[1:3, :])

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [18]:
print(a[:, 1:3])

[[ 2  3]
 [ 6  7]
 [10 11]]


In [19]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
a[[0, 2], :]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [21]:
a[[0, 2], [1, 2]]

array([ 2, 11])

In [22]:
a > 2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [23]:
a[a > 2]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])