In [31]:
!pip install numpy

distributed 1.21.8 requires msgpack, which is not installed.
You are using pip version 10.0.1, however version 18.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


In [32]:
import numpy as np

In [33]:
np.array([1, 2, 3])

array([1, 2, 3])

In [34]:
np.array([1.1, 2,4])

array([1.1, 2. , 4. ])

In [35]:
x = np.array([1, 2, 3, 4, 5])
x.shape

(5,)

In [43]:
x = np.array([
    [5, 6, 7],
    [8, 9, 10]
])
y = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [44]:
x * y

array([[ 5, 12, 21],
       [32, 45, 60]])

In [37]:
y.shape

(2, 3)

In [45]:
x[0][1]

6

In [50]:
x[0:2, 1:3]

array([[ 6,  7],
       [ 9, 10]])

In [63]:
x[x > 5]

array([ 6,  7,  8,  9, 10])

In [64]:
x.sum()

45